// preload：给本地页面与应用页面暴露最小桌面桥
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dshDesktop', {
    // 自绘标题栏：窗口控制
    winMinimize: () => ipcRenderer.send('dsh:win-minimize'),
    winMaximize: () => ipcRenderer.send('dsh:win-maximize'),
    winClose: () => ipcRenderer.send('dsh:win-close'),
    winIsMaximized: () => ipcRenderer.invoke('dsh:win-is-maximized'),
    onWinMaximizedChange: (cb) => ipcRenderer.on('dsh:win-maximized-change', (_e, v) => cb(v)),
    restart: () => ipcRenderer.send('dsh:restart'),
    quit: () => ipcRenderer.send('dsh:quit'),
    reloadHarness: () => ipcRenderer.invoke('dsh:reload-harness'),
    reloadHarnessSoft: (msg) => ipcRenderer.invoke('dsh:reload-harness-soft', msg),
    logPath: () => ipcRenderer.invoke('dsh:get-log-path'),
    openMcp: () => ipcRenderer.send('dsh:open-mcp'),
    openPlugins: () => ipcRenderer.send('dsh:open-plugins'),
    openSettings: (tab) => ipcRenderer.send('dsh:open-settings', tab),
    onSettingsTab: (cb) => ipcRenderer.on('dsh:settings-tab', (_e, tab) => cb(tab)),
    detectMcp: () => ipcRenderer.invoke('dsh:detect-mcp'),
    mcpUpsert: (id, config) => ipcRenderer.invoke('dsh:mcp-upsert', id, config),
    mcpRemove: (id) => ipcRenderer.invoke('dsh:mcp-remove', id),
    listPlugins: () => ipcRenderer.invoke('dsh:list-plugins'),
    pluginJobStatus: () => ipcRenderer.invoke('dsh:plugin-job-status'),
    onPluginJobEvent: (cb) => ipcRenderer.on('dsh:plugin-job-event', (_e, job) => cb(job)),
    installPlugin: (pkg) => ipcRenderer.invoke('dsh:install-plugin', pkg),
    uninstallPlugin: (pkg, force) => ipcRenderer.invoke('dsh:uninstall-plugin', pkg, force),
    disabledDefaultsList: () => ipcRenderer.invoke('dsh:disabled-defaults-list'),
    defaultPluginsList: () => ipcRenderer.invoke('dsh:default-plugins-list'),
    disabledDefaultsAdd: (pkg) => ipcRenderer.invoke('dsh:disabled-defaults-add', pkg),
    disabledDefaultsRestore: (pkg) => ipcRenderer.invoke('dsh:disabled-defaults-restore', pkg),
    marketDisabledList: () => ipcRenderer.invoke('dsh:market-disabled-list'),
    marketDisabledAdd: (repo) => ipcRenderer.invoke('dsh:market-disabled-add', repo),
    marketDisabledRemove: (repo) => ipcRenderer.invoke('dsh:market-disabled-remove', repo),
    updatePlugin: (name, version) => ipcRenderer.invoke('dsh:plugin-update', name, version),
    pluginUpdateCheck: (force) => ipcRenderer.invoke('dsh:plugin-update-check', force === true),
    aiInstallPlugin: (pkg) => ipcRenderer.invoke('dsh:ai-install-plugin', pkg),
    aiInstallReady: () => ipcRenderer.invoke('dsh:ai-install-ready'),
    marketList: (force) => ipcRenderer.invoke('dsh:market-list', force === true),
    resolvePlugin: (repo) => ipcRenderer.invoke('dsh:resolve-plugin', repo),
    repairSessions: () => ipcRenderer.invoke('dsh:repair-sessions'),
    sessionRollbackList: (force) => ipcRenderer.invoke('dsh:session-rollback-list', force === true),
    sessionDeleteList: (force) => ipcRenderer.invoke('dsh:session-delete-list', force === true),
    deleteSession: (file) => ipcRenderer.invoke('dsh:session-delete', file),
    sessionTrashList: (force) => ipcRenderer.invoke('dsh:session-trash-list', force === true),
    deleteTrashSession: (dir) => ipcRenderer.invoke('dsh:session-trash-delete', dir),
    restoreTrashSession: (dir) => ipcRenderer.invoke('dsh:session-trash-restore', dir),
    getTrashPath: () => ipcRenderer.invoke('dsh:get-trash-path'),
    openTrashFolder: () => ipcRenderer.invoke('dsh:open-trash-folder'),
    rollbackTrashList: () => ipcRenderer.invoke('dsh:rollback-trash-list'),
    rollbackTrashRestore: (stamp, rel) => ipcRenderer.invoke('dsh:rollback-trash-restore', stamp, rel),
    readImageFile: (filePath) => ipcRenderer.invoke('dsh:read-image-file', filePath),
    readClipboardImage: () => ipcRenderer.invoke('dsh:read-clipboard-image'),
    visionConfigSave: (payload) => ipcRenderer.invoke('dsh:vision-config-save', payload),
    visionConfigStatus: () => ipcRenderer.invoke('dsh:vision-config-status'),
    visionConfigSaveKey: (payload) => ipcRenderer.invoke('dsh:vision-key-save', payload),
    sessionRollback: (file) => ipcRenderer.invoke('dsh:session-rollback', file),
    sessionRollbackByMessage: (sessionId, messageId) => ipcRenderer.invoke('dsh:session-rollback-by-message', sessionId, messageId),
    sessionRollbackByUserMessage: (sessionId, userMessageId) => ipcRenderer.invoke('dsh:session-rollback-by-user-message', sessionId, userMessageId),
    sessionRollbackByUserMessageSoft: (sessionId, userMessageId) => ipcRenderer.invoke('dsh:session-rollback-by-user-message-soft', sessionId, userMessageId),
    sessionRollbackByUserMessageHot: (sessionId, userMessageId) => ipcRenderer.invoke('dsh:session-rollback-by-user-message-hot', sessionId, userMessageId),
    rewindList: (filter) => ipcRenderer.invoke('dsh:rewind-list', filter),
    rewindPreview: (id) => ipcRenderer.invoke('dsh:rewind-preview', id),
    rewindExecute: (id, signature) => ipcRenderer.invoke('dsh:rewind-execute', id, signature),
    rewindUndo: (guardId) => ipcRenderer.invoke('dsh:rewind-undo', guardId),
    checkUpdate: () => ipcRenderer.invoke('dsh:check-update'),
    updateDownload: (downloadUrl) => ipcRenderer.invoke('dsh:update-download', downloadUrl),
  });
